### ISSUE TITLE
JS-Error in list view in conjunction with 2.6.x Date Fields (moment.js)

### ISSUE THREAD

**Issue by animaux** [symphonists/unpublishedfilter#7]
When using a date field in an installation recently updated from 2.2.5 to 2.6.1 I get the following JS-Error in the console:

[Error] TypeError: undefined is not a function (evaluating 'moment().utcOffset()')
  (anonym funksjon) (symphony.min.js, line 97)
  each (symphony.min.js, line 14)
  each (symphony.min.js, line 14)
  (anonym funksjon) (symphony.min.js, line 97)
  execute (symphony.min.js, line 32)
  dispatch (symphony.min.js, line 32)
  dispatch (symphony.min.js, line 32)
  parse (symphony.min.js, line 37)
  render (symphony.min.js, line 96)
  (anonym funksjon) (symphony.min.js, line 97)
  k (symphony.min.js, line 24)
  fireWith (symphony.min.js, line 24)
  ready (symphony.min.js, line 24)
  g (symphony.min.js, line 14)

… as long as `unpublishedfilter` is activated.

https://github.com/symphonycms/symphony-2/issues/2388

**Comment by nitriques** [comment]
What happens if you comment out those 4 lines: https://github.com/symphonists/unpublishedfilter/blob/master/assets/unpublishedfilter.publish.js#L54-L57 ?

**Comment by animaux** [comment]
The error persists.

23.03.2015 kl. 22:08 skrev Nicolas Brassard <notifications@github.com>:

**Comment by animaux** [comment]
Commenting out [Line 27](https://github.com/symphonists/unpublishedfilter/blob/master/extension.driver.php#L27) of the `extension.driver.php` helps though :) not sure about any side-effects …

**Comment by nitriques** [comment]
Haaaa you found it. We must check if > 2.6 and NOT override moment.js.... damn!!

Will fix ASAP.

**Comment by nitriques** [comment]
Do you still get the benefit of "dim if in the future" ?

**Comment by animaux** [comment]
Brilliant, many thanks!

23.03.2015 kl. 22:23 skrev Nicolas Brassard <notifications@github.com>:

**Comment by nitriques** [comment]
Thanks to *you*!

**Comment by animaux** [comment]
Did a quick check, apparently not. (Not sure if I didn�t mess with something else to prevent this anyway.)


23.03.2015 kl. 22:24 skrev Nicolas Brassard <notifications@github.com>:

**Comment by nitriques** [comment]
Hum... 'cause your field's name is Datum, it should get picked up. https://github.com/symphonists/unpublishedfilter/blob/master/assets/unpublishedfilter.publish.js#L6

**Comment by animaux** [comment]
Right. Still it doesn’t seem to work. (I never quite liked that functionality anyway, at least not that it is not optional (see other issue :) ))

![skjermbilde 2015-03-23 kl 22 44 54](https://cloud.githubusercontent.com/assets/446874/6791339/84cad40c-d1ae-11e4-9fe3-a9c5960abfe4.png)

**Comment by nilshoerrmann** [comment]
@nitriques: This extension used an older version of Moment.js. So maybe the API changed an this line doesn't work anymore: https://github.com/symphonists/unpublishedfilter/blob/master/assets/unpublishedfilter.publish.js#L54

**Comment by nitriques** [comment]
@nilshoerrmann thanks for the heads up.

@animaux it is optional! But you would have to rename your field. Let's continue that discussion in the other issue :)

For now, I will remove moment for 2.6+ setups and release a new version.

**Comment by animaux** [comment]
@nitriques thanks! Sounds like a plan.

**Comment by nitriques** [comment]
Great!

**Comment by nitriques** [comment]
Thanks Nils!
